spring:
  application:
    name: users-crud
  datasource:
    url: jdbc:mysql://localhost:3309/users-crud
    username: root
    password: laura
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089

logging:
  level:
    org.springframework.web: DEBUG
debug: true
jwt:
  secret: clavesecreta123lauramoyanoesmuylinda
  expiration: 3600000


